name = "MNMM Create"
author = "Katsuro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "35007daf6c5dcc23e455eae785a150caf3c3d46338e9ecd64cf721169a2a0a01"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
