name = "MNMM Create"
author = "Katsuro"
version = "1.0.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "58d80c0688f343d80f1d2f559ed3f6684fc3225e97e0d43b797fe3348d0c681d"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.233"
