name = "MNMM Create"
author = "Katsuro"
version = "2.3.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "7278174bcad61d13d8290631e96503930b08beafeb431d8840b3e57ed4fbadae"

[versions]
minecraft = "1.21.1"
neoforge = "21.1.249"
